### Question 1: Create a null vector of size 10 but the fifth value which is 1.

In [17]:
import numpy as np

In [3]:
a = np.array([np.nan] * 10)
a[4] = 1
a


array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

### Question 2: Ask users for 2 numbers and Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [4]:
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

# Now I will be making a new array.
arr = np.random.random((a,b))
print(arr)
print(arr.mean())

[[0.42459708 0.57421741]
 [0.34817951 0.40820549]]
0.4387998729236458


### Question 3: Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.


In [5]:
m = int(input())
n = int(input())


def function(m,n):

    arr = np.ones((m,n))

    arr[1:-1,1:-1] = 0
    return arr
function(m,n)

array([[1., 1.],
       [1., 1.]])

### Question 4 : Create a vector of size 10 with values ranging from 0 to 1, both excluded. 

In [6]:
np.random.random((10))

array([0.97540304, 0.19412737, 0.47261775, 0.83189636, 0.43695876,
       0.73293232, 0.59900758, 0.80593263, 0.32035012, 0.49511103])

### Question 5 : Make an identity Matrix of size m

In [7]:
number = int(input())

np.identity(number)

array([[1., 0.],
       [0., 1.]])

### Question 6 : Create a 5x5 matrix with row values ranging from 0 to 4.


In [8]:
z = np.zeros((5,5))
z += np.arange(5)
z


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

### Question 7 : Consider a random integer (in range 1 to 100) vector with shape (10, 2) representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type. I

In [9]:
arr = np.random.randint(1,100,(10,2))
point = np.array([2,3])
dist = []

In [10]:




print(arr)
arr = np.sqrt(arr)
print(arr)


[[75 92]
 [10 27]
 [ 1 50]
 [ 1  4]
 [15 41]
 [48 59]
 [28 99]
 [92 11]
 [15 67]
 [24 16]]
[[8.66025404 9.59166305]
 [3.16227766 5.19615242]
 [1.         7.07106781]
 [1.         2.        ]
 [3.87298335 6.40312424]
 [6.92820323 7.68114575]
 [5.29150262 9.94987437]
 [9.59166305 3.31662479]
 [3.87298335 8.18535277]
 [4.89897949 4.        ]]


### Question 8: Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [11]:
print(np.unravel_index(100, (6,7,8)))
## Now lets confirm this.
np.zeros((6,7,8))


(1, 5, 4)


array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.,

### Question 9: Take Space seperated input of numbers and print a reversed numpy array as output. 

In [12]:
a = input().split(' ')



In [13]:
a = np.array(a,dtype=np.int64)

In [14]:
a = np.flip(a)

### Question 10: Make a function to calculate the Softmax function. 

Only take in a 1D Numpy array, else give an error.

In [15]:
arr = np.array([86.03331084, 37.7285648, 48.64908087, 87.16563062, 38.40852563, 37.20006318])


def softmax(arr):
    if type(arr) != np.ndarray:
        raise TypeError("Only Numpy arrays allowed to be inputed.")
    elif arr.ndim > 1:
        raise TypeError("Only 1D arrays accepted.")
    sum = np.sum(arr)
    softmax = []
    for i in arr:
        s = (i / sum)
        softmax.append(s)
    

    return softmax


a = softmax(arr)

np.sum(a)



1.0

### Question 11: Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.

#### In *args I can give as many arguments as I want to.

In [16]:
def vertical_stack(*args):
    for i in args:
        if type(i) != np.ndarray:
            raise TypeError("Only Numpy arrays allows ")
    return np.vstack(*args)


a = np.arange(1,11)
b = np.repeat(1,10)
vertical_stack((a,b))

TypeError: Only Numpy arrays allows 

In [ ]:
a
b

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Question 12: Substract the mean of each row from the matrix.

In [ ]:
x = np.random.random((5,4))
mean = x.mean(axis=1).reshape(5,1)

print(mean)
print(x)
print(x - mean)

[[0.54583403]
 [0.56995348]
 [0.55878522]
 [0.31821915]
 [0.58291991]]
[[0.66807796 0.60758615 0.56587412 0.34179791]
 [0.3597857  0.7858721  0.41957624 0.71457989]
 [0.54924541 0.61632351 0.17104371 0.89852824]
 [0.31642732 0.02794483 0.01852399 0.90998049]
 [0.60485515 0.54949593 0.67701926 0.50030929]]
[[ 0.12224392  0.06175212  0.02004008 -0.20403612]
 [-0.21016778  0.21591862 -0.15037724  0.1446264 ]
 [-0.0095398   0.05753829 -0.38774151  0.33974303]
 [-0.00179183 -0.29027433 -0.29969517  0.59176133]
 [ 0.02193524 -0.03342398  0.09409936 -0.08261061]]


### Question 13: Swap column-1 of array with column-2 in the array.

In [ ]:
x = np.random.random((5,4))
new_order = [1,0,2,3]
rearranged_array = x[:, new_order]
print(x)
print(rearranged_array) 

[[0.83607569 0.09142741 0.44003314 0.62169761]
 [0.14899227 0.00548808 0.92935301 0.48139896]
 [0.31147376 0.74176837 0.2233547  0.74159745]
 [0.37865403 0.51143438 0.85165918 0.80237324]
 [0.49954519 0.7758328  0.19548236 0.01084187]]
[[0.09142741 0.83607569 0.44003314 0.62169761]
 [0.00548808 0.14899227 0.92935301 0.48139896]
 [0.74176837 0.31147376 0.2233547  0.74159745]
 [0.51143438 0.37865403 0.85165918 0.80237324]
 [0.7758328  0.49954519 0.19548236 0.01084187]]


### Question 14: Replace the odd elements of an array with -1. 

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[a % 2 == 1] = -1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### Question 15: Given two arrays of same shape make an array of max out of two arrays. (Numpy way)

In [ ]:
a = np.array([6,3,1,5,8])
b = np.array([3,2,1,7,2])

In [ ]:
print(a)
b

[6 3 1 5 8]


array([3, 2, 1, 7, 2])

In [ ]:
a[b > a] = b[b > a]

In [ ]:
a

array([6, 3, 1, 7, 8])

### Question 16 : Find the nearest element in the given array to an integer.

In [ ]:
a = 23
arr = np.array([10, 17, 24, 31, 38, 45, 52, 59])
abs(arr - a).argmin()


2

### Question 17: Replace multiples of 0 or 5 with 0 from the given array.

In [ ]:
arr = np.array([12, 3, 4, 5, 6, 7, 9])
arr[(arr % 5 == 0) | (arr % 3 == 0)] = 0

In [ ]:
arr

array([0, 0, 4, 0, 0, 7, 0])

### Question 18: Double the array elements at a given index 

arr = np.arrange(10)
indices = [0,3,4,8]


Result -> [0, 1, 2, 6, 8, 5, 6, 7, 8, 18]

In [ ]:
arr = np.arange(10)
indices = [0,3,4,8]
arr[indices] *= 2


In [ ]:
arr

array([ 0,  1,  2,  6,  8,  5,  6,  7, 16,  9])

### Question 19: 

array = [1,2,3]
result array -> [1 1 1 2 2 2 3 3 3]

In [ ]:
arr = np.array([1,2,3,4,5])

indexes = []
for i in range(len(arr)):
    indexes.extend([i] * len(arr))
    
arr[indexes]

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5,
       5, 5, 5])

### Question 20: You are given an array which has some nan values. Your Job is to fill those nan values with most common element in the array. 

In [ ]:
arr = np.array ([[1,2,np.nan], [4,2,6], [np.nan, np.nan, 5]])


2

In [ ]:
arr[np.isnan(arr)] = np.ravel(arr).argmax()
arr

array([[1., 2., 2.],
       [4., 2., 6.],
       [2., 2., 5.]])

In [ ]:
np.nan_to_num(arr,np.ravel(arr).argmax())

array([[1., 2., 2.],
       [4., 2., 6.],
       [2., 2., 5.]])

### Question 21: Take 2 shapes and check if they can be broadcasted or not. 

In [ ]:
a = [1,2,3]
b = [2,2,4,5]

def check_broadcast(a,b):
    for ai, bi in zip(a,b):
        if ai != bi and ai != 1 and bi != 1:
            return False
        
    return True



1 2
2 2
3 4


### Question 22: Create a random 3x4 matrix with value between 0-100. And perform below tasks.

i. Sort this matrix based on max value in each row. 

ii. Sort based on elements value.

##### i.

In [59]:
# Sorting on the basis of that maximum in each row.

arr = np.array([[ 4,  4,  5,  69],[ 2,  3,  9, 100],[ 1,  7,  8, 11]])
arr

array([[  4,   4,   5,  69],
       [  2,   3,   9, 100],
       [  1,   7,   8,  11]])

In [62]:
np.array(sorted(arr, key = lambda x: max(x))) ## IMPORTANT IMPORTANT !!!!

array([[  1,   7,   8,  11],
       [  4,   4,   5,  69],
       [  2,   3,   9, 100]])

##### ii.

In [70]:
s = np.ravel(arr)
s.reshape(3,4)

array([[  1,   2,   3,   4],
       [  4,   5,   7,   8],
       [  9,  11,  69, 100]])

### Question 23: There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.

i. Add a new column to the 2D array - Marks of an extra subject.
        
        extra_subject = [41, 87, 72, 36, 92]

ii. Add two new students marks in respective subjects. (one subject added in above task) 

iii. Add extra column with sum of all subjects(5-subjects) marks

iv. Sort the array(non-ascending order) on total marks column.

#### i

In [89]:
arr = np.random.randint(0,101,20).reshape(5,4)
arr

array([[53, 73, 63, 38],
       [38, 44, 51, 18],
       [60, 43, 15, 15],
       [27, 62, 69, 47],
       [ 3, 34, 26, 88]])

In [94]:
extra_subject = np.array([41, 87, 72, 36, 92]).reshape(5,1)

In [102]:
arr = np.hstack((arr,extra_subject))

#### ii

In [103]:
stu1 = np.array([77, 83, 98, 95, 89]).reshape(1,5)
stu2 = np.array([92, 71, 52, 61, 53]).reshape(1,5)
print(stu1, stu2)

[[77 83 98 95 89]] [[92 71 52 61 53]]


In [110]:
arr = np.vstack((arr,stu1,stu2))

#### iii

In [120]:
sum = np.sum(arr,axis=1)
sum = sum.reshape(7,1)

In [122]:
print(arr)
print(sum)

[[53 73 63 38 41]
 [38 44 51 18 87]
 [60 43 15 15 72]
 [27 62 69 47 36]
 [ 3 34 26 88 92]
 [77 83 98 95 89]
 [92 71 52 61 53]]
[[268]
 [238]
 [205]
 [241]
 [243]
 [442]
 [329]]


In [125]:
arr = np.hstack((arr,sum))

#### iv

In [128]:
sorted(arr, key = lambda x: x[-1],reverse=True)

[array([ 77,  83,  98,  95,  89, 442]),
 array([ 92,  71,  52,  61,  53, 329]),
 array([ 53,  73,  63,  38,  41, 268]),
 array([  3,  34,  26,  88,  92, 243]),
 array([ 27,  62,  69,  47,  36, 241]),
 array([ 38,  44,  51,  18,  87, 238]),
 array([ 60,  43,  15,  15,  72, 205])]

### Question 24: Find Unique arrays from a 2D array column and row wise.

In [139]:
arr = np.array([[1,2,1,3,1,1],
                [0,9,0,2,8,8],
                [1,2,1,8,8,8],
                [1,2,1,3,1,1]])

In [140]:
# Unique rows.
np.unique(arr, axis=0)

array([[0, 9, 0, 2, 8, 8],
       [1, 2, 1, 3, 1, 1],
       [1, 2, 1, 8, 8, 8]])

In [141]:
# Unique Columns
np.unique(arr,axis = 1)

array([[1, 1, 2, 3],
       [0, 8, 9, 2],
       [1, 8, 2, 8],
       [1, 1, 2, 3]])

#### Question 25: Get two numbers of Numpy array having elements larger than x.

arr = np.array([[1,2,3,4,5],
                [10,-3,30,4,5],
                [3,2,5,-4,5],
                [9,7,3,6,5]])

X = 6

In [144]:
arr = np.array([[1,2,3,4,5],
                [10,-3,30,4,5],
                [3,2,5,-4,5],
                [9,7,3,6,5]])

X = 6

In [181]:
np.where(np.any(arr > 6, axis=1))

(array([1, 3]),)

#### Question 26: You are given a array. You have to find the minimum and maximum array element and remove that from the array.

np.random.Seed(400)

arr = np.random.randint(100, 1800, 200).reshape((1, 200))

In [194]:
np.random.seed(400)

arr = np.random.randint(100, 1800, 200).reshape((1, 200))
arr

array([[ 448, 1587,  418, 1053,  240, 1111,  507, 1386,  345,  236,  719,
        1315,  298, 1663,  458,  387,  262,  613,  267,  882, 1205, 1449,
         790,  635,  967, 1301, 1494, 1010,  336,  920,  295, 1581, 1029,
        1080, 1530,  385,  353,  592, 1040, 1072,  137, 1364,  222,  215,
         472,  459,  617,  649, 1070,  914,  932, 1669,  921, 1514,  527,
         972, 1302,  307,  840,  958,  246, 1079,  449,  251,  103, 1651,
         824,  356,  825, 1197,  323, 1396, 1077,  710, 1488, 1268, 1066,
         763, 1659,  436,  774, 1195,  469, 1202,  458, 1648,  211, 1795,
         270, 1068,  308, 1255,  952,  514,  699, 1726,  433,  900, 1054,
         373,  318,  265, 1527,  320,  230, 1348,  967,  620, 1013, 1767,
        1036, 1551, 1141, 1590, 1147, 1611,  227,  757, 1352,  930,  325,
        1753, 1450, 1042, 1034, 1538, 1013, 1320,  879,  575,  936,  705,
        1233,  191, 1767, 1094,  510, 1537, 1652,  559, 1682,  528,  395,
         525,  922,  136,  496,  225, 

In [191]:
max_element = arr.argmax()
min_element = arr.argmin()

In [195]:
np.delete(arr,max_element)
np.delete(arr,min_element)

array([ 448, 1587,  418, 1053,  240, 1111,  507, 1386,  345,  236,  719,
       1315,  298, 1663,  458,  387,  262,  613,  267,  882, 1205, 1449,
        790,  635,  967, 1301, 1494, 1010,  336,  920,  295, 1581, 1029,
       1080, 1530,  385,  353,  592, 1040, 1072,  137, 1364,  222,  215,
        472,  459,  617,  649, 1070,  914,  932, 1669,  921, 1514,  527,
        972, 1302,  307,  840,  958,  246, 1079,  449,  251, 1651,  824,
        356,  825, 1197,  323, 1396, 1077,  710, 1488, 1268, 1066,  763,
       1659,  436,  774, 1195,  469, 1202,  458, 1648,  211, 1795,  270,
       1068,  308, 1255,  952,  514,  699, 1726,  433,  900, 1054,  373,
        318,  265, 1527,  320,  230, 1348,  967,  620, 1013, 1767, 1036,
       1551, 1141, 1590, 1147, 1611,  227,  757, 1352,  930,  325, 1753,
       1450, 1042, 1034, 1538, 1013, 1320,  879,  575,  936,  705, 1233,
        191, 1767, 1094,  510, 1537, 1652,  559, 1682,  528,  395,  525,
        922,  136,  496,  225,  895, 1287,  908, 14

#### Question 27: You are given an arrays. You have to limit this array's elements between 100 to 200. arr € [100, 700]. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [196]:
arr = np.random.randint(100,701,50)

In [202]:
arr = np.clip(arr,a_min = 100,a_max = 200)

In [204]:
arr = np.sort(arr)

In [205]:
np.cumsum(arr)

array([ 100,  223,  354,  487,  633,  786,  943, 1143, 1343, 1543, 1743,
       1943, 2143, 2343, 2543, 2743, 2943, 3143, 3343, 3543, 3743, 3943,
       4143, 4343, 4543, 4743, 4943, 5143, 5343, 5543, 5743, 5943, 6143,
       6343, 6543, 6743, 6943, 7143, 7343, 7543, 7743, 7943, 8143, 8343,
       8543, 8743, 8943, 9143, 9343, 9543])

#### Question 28: You are given a array (arr € [0, 11). First you have round off the elements upto 3 decimal places and compare that

• Oth percentile == minimum value of the array

• 100th percentile == maximum value of the array

• also find the difference betwen 51th percenile and 50th percentile values

In [213]:
arr = np.random.random(100)
arr.round(decimals=3)
np.percentile(arr,0) == np.min(arr)
np.percentile(arr,100) == np.max(arr)
np.percentile(arr,51) - np.percentile(arr,50)


0.002975738570207054