## This sessions is on Great Numpy Functions 

NOTES : https://colab.research.google.com/drive/1PUW-yXxbkSYgvlhC5_zf30aOVyKYo9AC?usp=sharing

### np.sort

returns a sorted numpy array. 

Documentation : https://numpy.org/doc/stable/reference/generated/numpy.sort.html


In [4]:
import numpy as np
a = np.random.randint(1,100,15) # 1D Array. 
a


array([19, 56, 66, 25, 48,  7, 38, 44, 56, 85, 81, 55, 40, 14, 50])

In [7]:
np.sort(a,kind='mergesort') ## The sorting technique is optional to select. Default is Quick sort. 

array([ 7, 14, 19, 25, 38, 40, 44, 48, 50, 55, 56, 56, 66, 81, 85])

In [5]:
b = np.random.randint(1,100,24).reshape(6,4) # 2D Array.
b

array([[93, 79, 81, 10],
       [49, 97, 30, 80],
       [11, 84, 49, 12],
       [42, 28, 31, 65],
       [60, 60, 64, 12],
       [60, 71, 15, 48]])

In [16]:
## Sorting b 
np.sort(b) ## This is default sorting and does it in each rows. 
np.sort(b,axis = 0) ## This is if I want to do column wise sorting.
np.sort(b,axis = 0, kind= 'mergesort') ## Just adding some other features. 


## Now if I want to sort in the descending order then.
print(np.sort(a)[::-1]) ## THIS DOES NOT WORK WITH ANYTHING MORE THAN ONE DIMENSIONAL. 



[85 81 66 56 56 55 50 48 44 40 38 25 19 14  7]


### np.append

This appends the mentioned values at the end of the array. (I can specify the axis that I would like to append to.)

Documentation : https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [17]:
np.append(a,200)

array([ 19,  56,  66,  25,  48,   7,  38,  44,  56,  85,  81,  55,  40,
        14,  50, 200])

In [25]:
np.append(b,np.ones((b.shape[0],1)), axis = 1)

array([[93., 79., 81., 10.,  1.],
       [49., 97., 30., 80.,  1.],
       [11., 84., 49., 12.,  1.],
       [42., 28., 31., 65.,  1.],
       [60., 60., 64., 12.,  1.],
       [60., 71., 15., 48.,  1.]])

#### if I want to use this then go throught the documentation and use . 

### np.concatinate 

Concatinates a sequence of arrays along an existing axis. (GENERALLY USED WITH 2D ARRAYS) [THIS IS USED IN PLACE OF VSTACK AND HSTACK"]

Documentation : https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [27]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c,d)

[[0 1 2]
 [3 4 5]] [[ 6  7  8]
 [ 9 10 11]]


In [30]:
np.concatenate((c,d))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### np.unique

using this I can get the unique elements from an array. 

Documentation : https://numpy.org/doc/stable/reference/generated/numpy.unique.html#numpy-unique

In [31]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6, 6])
f = np.array([[1,2,3,1], [1,2,3,2]])

In [33]:
np.unique(e)
np.unique(f)

array([1, 2, 3])

### np.expand_dims

Using this I can expand the dimensions of my array.    

Documentation : https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [34]:
a

array([19, 56, 66, 25, 48,  7, 38, 44, 56, 85, 81, 55, 40, 14, 50])

In [37]:
np.expand_dims(a,axis = 0)

array([[19, 56, 66, 25, 48,  7, 38, 44, 56, 85, 81, 55, 40, 14, 50]])

#### It is used to expand the dimensions while building input arrary to input in ML / DL algorithms. 

### np.where 

It returns an array of indices where the condition is met.

Documentation : https://numpy.org/doc/stable/reference/generated/numpy.where.html


In [55]:
a

array([19,  0,  0, 25, 48,  7, 38, 44,  0,  0,  0,  0, 40, 14, 50])

In [56]:
np.where(a > 50)

(array([], dtype=int64),)

#### np.where can be used for other applications as well. 

Lets say I want to replace all values that are > 50 by 0. 

Basically Making alterations to the indices  

In [57]:
#a[np.where(a > 50)] = 0
a


array([19,  0,  0, 25, 48,  7, 38, 44,  0,  0,  0,  0, 40, 14, 50])

In [58]:
## The same thing can also be done using np.where function. 
## np.where(condition, if true then, if false then)

#np.where(a>50, 0 , a )

In [59]:
## Now lets say I want all even numbers to be replaced by 0 and odd ones to be replaced by 1.

np.where(a % 2 == 0, 0, 1)

array([1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### np.argmax and np.argmin

argmax - argument max [returns the indices of the max element of the array]
argmin - argument min [returns the indices of the min element of the array]

Documentation - https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [73]:
a = np.random.randint(1,100,25)
np.argmax(a)


9

In [80]:
np.argmax(b,axis=0) ## This tells me the index after I guess taking the array and aking it just in 1 row and then finding the max. 


array([0, 1, 0, 1])

In [78]:
b

array([[93, 79, 81, 10],
       [49, 97, 30, 80],
       [11, 84, 49, 12],
       [42, 28, 31, 65],
       [60, 60, 64, 12],
       [60, 71, 15, 48]])

#### Similarily there is also argmin that can be used. 

### np.cumsum & np.cumprod

Cummulative Sum and Cummulative Product

Documentation : https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [89]:
np.cumsum(a)[-1]


1072

In [93]:
np.cumsum(b, axis = 1)

array([[ 93, 172, 253, 263],
       [ 49, 146, 176, 256],
       [ 11,  95, 144, 156],
       [ 42,  70, 101, 166],
       [ 60, 120, 184, 196],
       [ 60, 131, 146, 194]])

### np.percentile

It computes the nth Percentile of the given data.

Documentation : https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [101]:
np.percentile(a, 90)

83.60000000000001

In [102]:
a

array([23, 69, 80, 37, 17, 72, 75, 32, 67, 95, 88, 86, 72, 22,  7,  7,  3,
       15, 63, 61,  3, 13, 19, 45,  1])

### np.histogram 

Wont Graph the plot. It will just give me the data.

In [104]:
np.histogram(a, bins = [0,10,20,30,40,50,60,70,80,90,100])

(array([5, 4, 2, 2, 1, 0, 4, 3, 3, 1]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

### np.corrcoef


Returns Pearson correlation coefficient.

Documentation : https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

## There are some other functions that I can explore. They are in the notebook above. 

##### np.clip , np.delete