In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
np.array([1,2,3])

array([1, 2, 3])

### The arrange function in Numpy  

In [6]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### The Reshape Function in Numpy

In [7]:
np.arange(1, 13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### Lets say I want a function with all 1's

In [8]:
ones = np.ones((3,3))
zeros = np.zeros((3,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### The Linspace function in Numpy.

In [9]:
# (lower range , upper range, number of items that I want in the range)
np.linspace(-10,10,5) # These are equidistant points.



array([-10.,  -5.,   0.,   5.,  10.])

### To create an identity matrix

In [10]:
np.identity(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### IF I want to innitialise my array using random numbers.


In [11]:
np.random.random((3,3)) # This will have any number form 0 to 1 randomly at each point.

array([[0.59868203, 0.13491905, 0.92554329],
       [0.91032049, 0.79241315, 0.26459429],
       [0.74392169, 0.61424126, 0.01480287]])

## Important Array Attributes

### The ndim attribute - this is to know the dimension of the array.

In [12]:
a1 = np.arange(10)
a1.ndim

1

In [13]:
a2 = np.arange(12).reshape(6,2)
a2.ndim ## The answer is 2 as a matrix has 2 dimensions.


2

### The shape Attribute

In [14]:
a2.shape ## This tells me the rows and columns of the matrix / array. 

(6, 2)

### The size attribute

In [15]:
a2.size # Size Tells ,me the number of items in the array / matrix

12

### The dtype attribute. 

In [16]:
a2.dtype ## Type of all the items in my array / mat

dtype('int64')

#### IMPORTANT NOTE : NOW TO GET A LIST OF ALL OF MY ATTRIBUTES THEN JUST DO THIS - array_name. - Wait for a couple of seconds now and VS Code will show me all the attributes.

### Numpy astype Function : Used to change the datatype of my array.

In [17]:
a2.astype(np.float32) ## This is used to optimise my memory.

array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.],
       [ 6.,  7.],
       [ 8.,  9.],
       [10., 11.]], dtype=float32)

## NUMPY ARRAY OPERATIONS

#### All the arithmetic operators can be used on a numpy array. Eg - + / % *, etc

#### All Relational Operators also work in a Numpy array. Eg : >, <, !=, ==.

#### Vector Operations like a1 + a2, a1 - a2, a1 * a2, a1 ** a2 etc. All such things can be done on a numpy array / matrix

#### numpy.org/doc/stable/reterence/ufuncs.html : These are all the functions that Numpys has. It is impossible to remember everything look for functions as and when needed 

### Lets look at some important functions.

In [18]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Finding the max from the array. 

In [19]:
max = np.max(a2)
min = np.min(a2)
sum = np.sum(a2)
product = np.prod(a2)

In [20]:
print (product)

362880


##### Now lets say I want to find the max and min from the first row (1) and column (0)  

In [21]:
mini = np.min(a2,axis=1) # this gave me the minimum of each row in the form of a tuple.
print(mini[0]) # Minimum of row and and I can 

1


In [22]:
min_column = np.max(a2,axis=0)

In [23]:
min_column # Minimum values from all the columns .

array([7, 8, 9])

### Now lets look at how I can use statistical concepts on the array

In [24]:
np.std(a2) # this gets me the standard deviation of all the numbers to me. 

2.581988897471611

In [25]:
np.std(a2,axis=1) # this will give me the standard deviation of all the rows. 

array([0.81649658, 0.81649658, 0.81649658])

In [26]:
np.var(a2)

6.666666666666667

In [27]:
np.mean(a2)

5.0

### Log and exponentiation can also be done  

In [28]:
np.log(a2)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [29]:
np.exp(a2)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

### Floor , Ceil and Round Function

In [30]:
np.round(np.random.random((3,3)))

array([[1., 0., 0.],
       [0., 1., 1.],
       [0., 1., 1.]])

In [31]:
np.ceil(np.random.random((3,3)))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.floor(np.random.random((3,3)))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Indexing and Slicing

In [33]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [34]:
a1[0]

0

In [35]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
a2[1][2]

6

In [37]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [38]:
a3[1]

array([[4, 5],
       [6, 7]])

In [39]:
a2[:,2]

array([ 2,  6, 10])

In [40]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [41]:
a3= np.arange(27).reshape (3,3,3)
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [42]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

### Iterating over my Numpy array.

In [43]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

### nditer Function - Used to iter over each element in your array - No matter the dimension  

In [46]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## Reshaping Functions in Numpy:

### Transpose 

In [47]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [48]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [49]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Ravel Function: Will convert any n-Dimensional Array into a 1D array. 

In [50]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [51]:
for i in a2.ravel():
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


### Stacking 

In [52]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [53]:
np.hstack((a4,a5,a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11, 20, 21, 22, 23]])

In [54]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting - Opposite of Stacking

In [55]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [56]:
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]